name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t flipkart-chatbot .

      - name: Run Container Test
        run: docker run -d -p 5000:5000 flipkart-chatbot